FROM python:3.11.1

COPY requirements.txt ./
RUN pip install -r requirements.txt

ENV BOT_TOKEN=$BOT_TOKEN
ENV HISTORIC_CHANNEL=$HISTORIC_CHANNEL
ENV COMMAND_CHANNEL=$COMMAND_CHANNEL
ENV WAR_CHANNEL=$WAR_CHANNEL
ENV GENERAL_CHANNEL=$GENERAL_CHANNEL
ENV LOG_CHANNEL=$LOG_CHANNEL
ENV ADM_ROLE=$ADM_ROLE
ENV GEN_ROLE=$GEN_ROLE
ENV CAP_ROLE=$CAP_ROLE
ENV SERVER_ID=$SERVER_ID
ENV APP_ID=$APP_ID
ENV MONGO_CO=$MONGO_CO
ENV URL_HEALTH_CHECK=$URL_HEALTH_CHECK
ENV PORT_HEALTH_CHECK=$PORT_HEALTH_CHECK

RUN echo "ENV  $BOT_TOKEN"

COPY ./Discord-Bot .
EXPOSE 1000
CMD [ "python", "./main.py" ]