FROM python:3.11.1

ENV BOT_TOKEN=$BOT_TOKEN
ENV HISTORIC_CHANNEL=$HISTORIC_CHANNEL
ENV COMMAND_CHANNEL=$COMMAND_CHANNEL
ENV WAR_CHANNEL=$WAR_CHANNEL
ENV GENERAL_CHANNEL=$GENERAL_CHANNEL
ENV LOG_CHANNEL=$LOG_CHANNEL
ENV ADM_ROLE=$ADM_ROLE
ENV GEN_ROLE=$GEN_ROLE
ENV CAP_ROLE=$CAP_ROLE
ENV SERVER_ID=$SERVER_ID
ENV APP_ID=$APP_ID
ENV MONGO_CO=$MONGO_CO
ENV URL_HEALTH_CHECK=$URL_HEALTH_CHECK
ENV PORT_HEALTH_CHECK=$PORT_HEALTH_CHECK

RUN echo "ENV  $BOT_TOKEN"
RUN echo "ENV  $HISTORIC_CHANNEL"
RUN echo "ENV  $COMMAND_CHANNEL"
RUN echo "ENV  $WAR_CHANNEL"
RUN echo "ENV  $GENERAL_CHANNEL"
RUN echo "ENV  $LOG_CHANNEL"
RUN echo "ENV  $ADM_ROLE"
RUN echo "ENV  $GEN_ROLE"
RUN echo "ENV  $CAP_ROLE"
RUN echo "ENV  $SERVER_ID"
RUN echo "ENV  $APP_ID"
RUN echo "ENV  $MONGO_CO"
RUN echo "ENV  $URL_HEALTH_CHECK"
RUN echo "ENV  $PORT_HEALTH_CHECK"

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY ./Discord-Bot ./Discord-Bot
EXPOSE 1000
CMD [ "python", "./Discord-Bot/main.py" ]